import { DRAFT_COMPLIANCE_CODES } from '@threadsignal/drafts';
import { draftDetailSchema } from '../src/lib/phase4/schema';
export const phase4Ids = {
  organization: '11111111-1111-4111-8111-111111111111',
  brand: '22222222-2222-4222-8222-222222222222',
  draft: '33333333-3333-4333-8333-333333333333',
  version: '44444444-4444-4444-8444-444444444444',
  source: '55555555-5555-4555-8555-555555555555',
  opportunity: '66666666-6666-4666-8666-666666666666',
  persona: '77777777-7777-4777-8777-777777777777',
  claim: '88888888-8888-4888-8888-888888888888',
  check: '99999999-9999-4999-8999-999999999999',
};
export function draftFixture() {
  const i = phase4Ids;
  const date = '2026-09-16T00:00:00Z';
  const text =
    'Compare the output on your own product images before choosing a tool. ClarityScale supports batch processing. I work with the team behind ClarityScale.';
  return draftDetailSchema.parse({
    draft: {
      id: i.draft,
      organization_id: i.organization,
      brand_id: i.brand,
      opportunity_id: i.opportunity,
      persona_id: i.persona,
      status: 'ready',
      current_version: 1,
      verified_version: 1,
      current_content: text,
      strategy: 'Answer first and explain the documented feature.',
      brand_mentioned: true,
      disclosure_included: true,
      verification_status: 'pass',
      compliance_status: 'pass',
      approved_by: null,
      approved_at: null,
      rejection_reason: null,
      error_code: null,
      purged_at: null,
      created_at: date,
      updated_at: date,
    },
    versions: [
      {
        id: i.version,
        version: 1,
        content: text,
        source: 'ai',
        instruction: '',
        created_by: null,
        created_at: date,
      },
    ],
    claims: [
      {
        id: i.claim,
        draft_version_id: i.version,
        claim_text: 'ClarityScale supports batch processing.',
        status: 'verified',
        confidence: 'high',
        explanation: 'The included documentation states this capability.',
        source_chunk_ids: [i.source],
        evidence_kind: 'current_documentation',
        provenance: [
          {
            chunk_id: i.source,
            source_id: i.source,
            document_id: i.source,
            title: 'Batch guide',
            source_url: 'https://clarityscale.example/docs',
            filename: null,
            page_number: null,
            section_heading: 'Processing',
            updated_at: date,
            excerpt: 'ClarityScale supports batch processing.',
          },
        ],
      },
    ],
    checks: [
      {
        id: i.check,
        draft_version_id: i.version,
        status: 'pass',
        safe_to_approve: true,
        created_at: date,
        checks: DRAFT_COMPLIANCE_CODES.map((code) => ({
          code,
          status: 'pass',
          message: 'Synthetic fixture check passed.',
          suggested_fix: null,
        })),
      },
    ],
    jobs: [],
    persona: {
      name: 'Product specialist',
      real_role: 'employee',
      tone: 'Helpful and concise',
      custom_tone: '',
      reply_length: 'standard',
      technical_depth: 'balanced',
      default_disclosure: 'I work with the team behind ClarityScale.',
      allowed_first_person_statements: [],
      prohibited_statements: [],
    },
    opportunity: {
      id: i.opportunity,
      organization_id: i.organization,
      brand_id: i.brand,
      subreddit_id: i.source,
      status: 'new',
      summary: 'Team needs a batch image API.',
      user_need: 'Batch processing',
      intent_category: 'recommendation',
      risk_level: 'low',
      semantic_relevance: 90,
      buying_intent: 90,
      freshness: 90,
      engagement_velocity: 90,
      rule_fit: 90,
      competitor_context: 90,
      penalty_score: 0,
      final_score: 90,
      suggested_action: 'reply',
      is_blocked: false,
      risk_reasons: [],
      matched_capabilities: ['Batch processing'],
      missing_capabilities: [],
      matched_competitor_ids: [],
      reasoning_summary: 'Relevant knowledge matches the need.',
      knowledge_citations: [],
      evaluated_at: date,
      created_at: date,
      post: {
        id: i.source,
        title: 'Looking for a batch image API',
        body: 'Which API can process product images in batches?',
        permalink: 'https://www.reddit.com/r/SaaS/comments/fixture/',
        created_at_provider: date,
        score: 12,
        num_comments: 4,
        is_deleted: false,
        is_locked: false,
        is_archived: false,
      },
      subreddit: {
        id: i.source,
        name: 'saas',
        display_name: 'SaaS',
        description: 'Synthetic software community',
        subscriber_count: 1000,
        is_nsfw: false,
        last_synced_at: date,
      },
    },
    rules: [],
    review: { context_current: true, responsible_use_accepted: true },
  });
}
