/** Deliberately fictional, versioned company sources. These pages never make network requests. */
export const fixturePages = [
  {
    url: 'https://clarityscale.example/',
    title: 'ClarityScale AI product overview',
    text: `# ClarityScale AI\nClarityScale AI is a fictional image optimization and upscaling API for ecommerce teams and developers. It helps teams prepare catalog photography, resize product images, compress large assets and run asynchronous batch image processing. These are synthetic local demo documents, not claims about a real service.\n\n## Product capabilities\nThe API accepts JPEG, PNG and WebP product photographs. Developers submit a batch, receive a job identifier, and poll job status before downloading optimized images. Images may be enlarged two or four times. Transparent PNG backgrounds remain transparent. Output formats include JPEG, PNG and WebP. No video processing or GIF animation is supported.\n\n## Appropriate use\nEcommerce catalog managers use consistent image dimensions and compression presets. Application developers integrate the API into upload workflows. Human review remains necessary for image quality, copyright permission and accurate product representation. Generated details are estimates; upscaling cannot reliably recover information absent from the original image.`,
  },
  {
    url: 'https://clarityscale.example/docs',
    title: 'ClarityScale API documentation',
    text: `# API documentation\nClarityScale AI provides asynchronous batch image optimization and upscaling. Authenticate application requests with a project API token stored only on your server. Submit JPEG, PNG or WebP input and choose a two-times or four-times upscale factor.\n\n## Batch processing\nA batch accepts up to fifty images. Each submitted image must be at most twenty megabytes and twenty-five megapixels. The response returns a job identifier; poll the job endpoint for queued, processing, completed or failed status. Reuse the same idempotency key when retrying a request to avoid creating a second job. Retry rate-limited requests using the Retry-After response header.\n\n## Integration\nUse server-side uploads for private source images. Download completed outputs after checking status. Output links expire after twenty-four hours. Store outputs in your own storage if you need long-term retention. The fictional API does not provide permanent image hosting. Webhooks are not available in this demo specification; polling is the supported completion mechanism.`,
  },
  {
    url: 'https://clarityscale.example/pricing',
    title: 'ClarityScale demo pricing and credits',
    text: `# Demo pricing\nThis page describes fictional ClarityScale AI pricing for local testing. The Starter plan costs nineteen US dollars per month and includes one thousand image credits. The Team plan costs fifty-nine US dollars per month and includes five thousand image credits. One standard image optimization uses one credit; four-times upscaling uses two credits.\n\n## Usage and billing\nUnused credits expire at the end of the monthly billing period. There are no unlimited plans. A free evaluation includes fifty credits with no payment card. Requests stop when the credit allowance is exhausted; there are no automatic overage charges. Taxes and currency conversion are not modeled in this fixture.\n\n## Choosing a plan\nEstimate the number of source images and upscale operations before selecting a plan. Starter is intended for small catalogs and prototypes. Team suits larger catalogs and supports shared project access. These are ClarityScale product prices, separate from ThreadSignal subscription prices.`,
  },
  {
    url: 'https://clarityscale.example/limits',
    title: 'Image quality limitations and supported formats',
    text: `# Image quality and limits\nClarityScale AI cannot reconstruct text, faces or product details with guaranteed accuracy. Very compressed, blurred or tiny source images may still show artifacts after upscaling. Always compare output with the original and reject misleading product representations.\n\n## Unsupported inputs\nVideo, animated GIF, RAW camera files, SVG vectors and PDF documents are not accepted as image inputs. JPEG, PNG and WebP files are supported up to twenty megabytes and twenty-five megapixels each. A batch can contain at most fifty images.\n\n## Responsible use\nOnly process images you own or have permission to modify. Do not represent invented image details as verified facts. The tool does not remove watermarks and does not promise higher sales or search rankings. Human inspection is required before publishing product photography.`,
  },
  {
    url: 'https://clarityscale.example/security',
    title: 'Security, privacy and image retention',
    text: `# Security and privacy\nThe fictional ClarityScale service uses HTTPS for API transport and private object storage for uploaded source images. Project tokens must remain server-side and can be revoked from project settings. Never embed an API token in a public browser bundle.\n\n## Data retention\nOriginal uploads and processed outputs are removed after twenty-four hours. Customers must download outputs before their links expire. Image data is not used to train models in this synthetic product specification. Deleting a project revokes its project tokens and requests removal of retained images.\n\n## Scope\nNo SOC 2 certification, HIPAA compliance or regulatory certification is claimed. Customers with regulated data should obtain an appropriate written agreement before using any real image-processing vendor. This local fixture does not transmit customer documents or images to an external service.`,
  },
  {
    url: 'https://clarityscale.example/support',
    title: 'Support and troubleshooting FAQ',
    text: `# Support and troubleshooting\nClarityScale demo support documentation helps developers interpret failed image jobs. An unsupported format error means the uploaded file is not JPEG, PNG or WebP. An image too large error indicates either the twenty-megabyte file limit or twenty-five-megapixel resolution limit was exceeded.\n\n## Retry guidance\nRetry transient processing failures using the same idempotency key. Wait for the Retry-After duration when receiving a rate-limit response. Do not repeatedly submit a permanently invalid source image. For expired output links, submit a new job only if you still have rights to the original image.\n\n## Help availability\nThe fictional Starter plan includes email support on business days. Team includes prioritized email support. There is no twenty-four-hour response guarantee and no live-chat commitment. Provide a job identifier and a safe error code when requesting help; do not send API tokens or private image links.`,
  },
] as const;
